exclude:
  - CNAME
  - Gemfile
  - README.md
title: Skelp
analytics_account: UA-27505414-1
social_links:
  - email:
    href: mailto:contact@skelp.io
    class_prefix: email
    icon: fa-envelope-square
    text: Email
